### ISSUE TITLE
Integration fails to load

### ISSUE THREAD

**Issue by thomascandrian** [lukas-hetzenecker/home-assistant-zyxel-poe#9]
I'm not really sure what is going wrong here...

```
login_step2 = await self._session.post(self._url, data=login_check_data)
        text = await login_step2.text()
        _LOGGER.debug(f"Step 2 returned status code: {login_step2.status}, text: {text}")

        if 'OK' not in text:
            _LOGGER.warn("OK not found in login step 2")
            if is_retry:
                raise Exception("Login failed: %s" % login_step2.text)
            await self._login(is_retry=True)
        
        _LOGGER.debug("Logged in successfully")
```

Login semms fine, and it looks like there IS a OK in the response text (see below), but it is not recognized. I tried to remove the code which checks the login, but it fails with the html parser. Maybe the device response did change in recent updates?

```
2024-07-01 20:48:31.718 ERROR (MainThread) [homeassistant.components.switch] Error while setting up zyxel_poe platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/zyxel_poe/switch.py", line 79, in async_setup_platform
await poe_data.async_update()
File "/config/custom_components/zyxel_poe/switch.py", line 220, in _async_update
await self._login()
File "/config/custom_components/zyxel_poe/switch.py", line 166, in _login
await self._login(is_retry=True)
File "/config/custom_components/zyxel_poe/switch.py", line 165, in _login
raise Exception("Login failed: %s" % login_step2.text)
Exception: Login failed: <bound method ClientResponse.text of <ClientResponse(http://10.0.11.2/cgi-bin/dispatcher.cgi) [200 OK]>
<CIMultiDictProxy('Date': 'Mon, 01 Jul 2024 18:48:31 GMT', 'Server': 'Hydra/0.1.8', 'Accept-Ranges': 'bytes', 'Connection': 'close', 'Content-Security-Policy': "default-src 'self';script-src 'self' 'unsafe-inline' 'unsafe-eval';style-src 'self' 'unsafe-inline'; base-uri 'self'")>
>
```

Model Name: | GS1900-8HP
Revision: | B1
Firmware Version: | V2.60(AAHI.4) \| 05/24/2021

**Comment by quizzical86** [comment]
Try upgrading your firmware to V2.70 or 2.80

**Comment by quizzical86** [comment]
hi @lukas-hetzenecker just a little message to inform you that the latest firmware (V2.90) of the zyxel GS1900 switches seems to be compatible with your integration.
The firmware upgrade fixes also some security vulnerabilities, so seems wise to do the update!
And again a thanks for having developed it many years ago, it still serves me very well :-)

**Comment by lukas-hetzenecker** [comment]
Awesome, thanks for the heads up - will try to remotely upgrade the switches that I still have running :)

**Comment by quizzical86** [comment]
@lukas-hetzenecker I noted down the steps to follow for a firmware upgrade as it's not super straightforward. Sharing it here in case it helps:
- Log in to the switch, download a backup of the configuration (choose http mode) and save it somewhere
- Download the latest firmware on the zyxel website. Unzip the zip.
- On the switch, load the latest firmware (http mode, choose the .bix file) to the backup location (not the active one)
- When it is ready, go to the management section under firmware and choose the new firmware as active.
- In the switch, choose reboot
- In your router or with the Zyxel ZON utility (installation program is here https://www.zyxel.com/zyxel-file/ZON_Utility.zip ) look for what the IP of the Zyxel switch is now.
- Log in on that IP address and enter admin as login and 1234 as password
- You choose a new password (temporary) and then log in again with the temporary password.
- Go to configuration (under maintenance) and load the backed up configuration again.
- Now you can surf to the original IP address of the switch again and log in with the original login details.

**Comment by MaxRower** [comment]
> [@lukas-hetzenecker](https://github.com/lukas-hetzenecker) I noted down the steps to follow for a firmware upgrade as it's not super straightforward. Sharing it here in case it helps:
> 
>     * Log in to the switch, download a backup of the configuration (choose http mode) and save it somewhere
> 
>     * Download the latest firmware on the zyxel website. Unzip the zip.
> 
>     * On the switch, load the latest firmware (http mode, choose the .bix file) to the backup location (not the active one)
> 
>     * When it is ready, go to the management section under firmware and choose the new firmware as active.
> 
>     * In the switch, choose reboot
> 
>     * In your router or with the Zyxel ZON utility (installation program is here https://www.zyxel.com/zyxel-file/ZON_Utility.zip ) look for what the IP of the Zyxel switch is now.
> 
>     * Log in on that IP address and enter admin as login and 1234 as password
> 
>     * You choose a new password (temporary) and then log in again with the temporary password.
> 
>     * Go to configuration (under maintenance) and load the backed up configuration again.
> 
>     * Now you can surf to the original IP address of the switch again and log in with the original login details.

I am using GS1900 series switches for many years, and your way to upgrade the firmware seems way too complicated for me. Changing an admin password and restoring a configuration was never necessary! Just make sure your running configuration is saved (to the switch), so it will be used after rebooting the switch. Having a backup is helpful if something goes wrong, but it's not required for an update. After flashing a new firmware to the backup location, the switch asks if you want to reboot to it and make it the default, and that's all. No need to use the zyxel utility and the rest of your steps. I often do remote updates via VPN, and it never failed.
If you have a different IP after the update and have login with admin and 1234, it seems, you did not save the running config, and thus, you will have a clean config (or whatever config you saved last time) after the next reboot, like a factory reset.

**Comment by quizzical86** [comment]
Then I must be doing something wrong indeed. I also feel my approach is rather complicated but it's the way I get it to work.
How can I 'make sure the running configuration is saved to the switch'?
After flashing the firmware to the backup location, my switches just return to the firmware update screen, without any sort of confirmation, or request to reboot.
I have myself to go to the relevant menu to select it as the active firmware, and then navigate to the page to reboot. This somehow causes the switch to lose it's configuration...

**Comment by MaxRower** [comment]
There is a "Save" button on the top right side in the GUI.
After you are making changes to the config and checking, that everything is working as intended, you should press that. If you don't do it, they will be lost after a reboot or power failure.
Do you have javascript and/or popups disabled in your browser? That could prevent the normal flow of the upgrade.

**Comment by MaxRower** [comment]
Take a look at chapter 5.1 and 5.3.1 of the user manual.

**Comment by MaxRower** [comment]
BTW, I upgraded one GS1900-24E to a GS1900-24EP just because this integration existed. Nice work, @lukas-hetzenecker!
